# https://stackoverflow.com/questions/2090551/parse-query-string-in-javascript
# generated by js2coffee 2.1.0
window.getQueryVariable = (variable) ->
    query = window.location.search.substring(1)
    vars = query.split('&')
    i = 0
    while i < vars.length
        pair = vars[i].split('=')
        if decodeURIComponent(pair[0]) == variable
            return decodeURIComponent(pair[1])
        i++
    return

window.chatConfig =
    username: getQueryVariable('username')
    notify:
        chat: (getQueryVariable('chat') == 'true') || true
        subs: (getQueryVariable('subs') == 'true') || false
        subanniversary: (getQueryVariable('subannv') == 'true') || false
        hosts: (getQueryVariable('hosts') == 'true') || false
    maxmessages: Number(getQueryVariable('maxmsgs')) || 5
    emotes:
        twitch: if (getQueryVariable('twitchemotes') == 'false') is true then false else true
        bttv: (getQueryVariable('bttvemotes') == 'true') || false

client = new tmi.client
    options:
        debug: true
    connection:
        reconnect: true
        secure: if location.protocol is 'https:' then true else false
    channels: ['#' + window.chatConfig.username]

client.connect()

# input sanitizer
escapeHtml = (str) ->
    div = document.createElement 'div'
    div.appendChild document.createTextNode(str)
    return div.innerHTML

client.addListener 'chat', (channel, user, message) ->
    if window.chatConfig.notify.chat
        event = new CustomEvent('message', {'detail': {user: user, message: emoteParse(user, escapeHtml(message)), action: false}});
        document.dispatchEvent(event);

client.addListener 'action', (channel, user, message) ->
    if window.chatConfig.notify.chat
        event = new CustomEvent('message', {'detail': {user: user, message: emoteParse(user, escapeHtml(message)), action: true}});
        document.dispatchEvent(event);

client.addListener 'subscription', (channel, user) ->
    if window.chatConfig.notify.subs
        event = new CustomEvent('sub', {'detail': {user: user}});
        document.dispatchEvent(event);

client.addListener 'subanniversary', (channel, user, months) ->
    if window.chatConfig.notify.subanniversary
        event = new CustomEvent('subanniversary', {'detail': {user: user, months: months}});
        document.dispatchEvent(event);

client.addListener 'hosted', (channel, user, viewers) ->
    if window.chatConfig.notify.hosts
        event = new CustomEvent('host', {'detail': {user: user, viewers: viewers}});
        document.dispatchEvent(event);

client.addListener 'connected', (address, port) ->
    event = new CustomEvent('message', {'detail': {user: {username: 'Chat Overlay'}, message: 'Connected to twitch.tv servers!', action: false}});
    document.dispatchEvent(event);

client.addListener 'disconnected', (reason) ->
    event = new CustomEvent('message', {'detail': {user: {username: 'Chat Overlay'}, message: 'You have been disconnected from twitch.tv. (Reason: ' + reason + ').', action: false}});
    document.dispatchEvent(event);

# client.addListener 'join', (channel, username) ->
#     event = new CustomEvent('message', {'detail': {user: {username: 'Chat Overlay'}, message: 'Joined your channel chatroom (' + channel + ').', action: false}});
#     document.dispatchEvent(event);